//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcKutuphane.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCEZALAR
    {
        public int ID { get; set; }
        public Nullable<int> UYEID { get; set; }
        public Nullable<System.DateTime> BASLANGICTARIH { get; set; }
        public Nullable<System.DateTime> BITISTARIH { get; set; }
        public Nullable<decimal> PARA { get; set; }
        public Nullable<int> HAREKETID { get; set; }
    
        public virtual TBLHAREKET TBLHAREKET { get; set; }
        public virtual TBLUYELER TBLUYELER { get; set; }
    }
}
